# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - undprs142wa001

on:
  push:
    branches:
      - coazure
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7f8dec4346ea4b658cce446b56aa8224 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4a357068f81047549a8cb4cbb3f043a2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7f8dec4346ea4b658cce446b56aa8224 }}/coazure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'undprs142wa001'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_35f74667ab234cf0bc07c77cee9f8e16 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7f8dec4346ea4b658cce446b56aa8224 }}/coazure:${{ github.sha }}'